### ISSUE TITLE
Fishbot Casting and Looting Issues??

### ISSUE THREAD

**Issue by Curiousbu** [UltimateFishbot/UltimateFishbot#134] opened 2018-09-02 01:39 UTC
Everything about the latest version of Fishbot is working fine, except for the fact that it wont cast, or loot the fish if you cast manually. The casting keybind is set to 1 and it says that its casting, but in game there is no cast; just the cursor doing its spiraling search.

**Comment by disputed** [comment] 2018-09-02 03:48
Same Issue, but I have found that the command /cast fishing does not work currently in game which I am guessing is the root cause of this problem.

**Comment by NaNraptor** [comment] 2018-09-02 06:27
To fix the looting issue you  have 3 options:

1) enable auto looting from the game itself 
2) go to the bot settings menu and in one of the tabs choose 'shift loot' 
3) use an auto looting addon 

To fix your other issue:
Make sure that your fishing pole is equipped and is on your very first bar (or wherever the 1 key is bound to) - i cannot replicate that problem so that my best guess

**Comment by D34d3nd** [comment] 2018-09-02 14:51
Ok, I think I have found the issue because I was having the exact same problem as Curiousbu and disputed. When you click 'Start' in UFB, it will go ahead and start doing its thing in your windowed-WoW frame (spiral trying to find bobber). But, it will not cast eventhough I had the Fish button on 1. In order to get it to work, I had to focus the WoW window (i.e. click anywhere in WoW) and then start UFB using Ctrl+Shift+S (the pause/start key combo). Everything worked fine after that.

**Comment by NaNraptor** [comment] 2018-09-03 13:56
@D34d3nd yeah the WOW window will of course have to be focused. This used to be a feature but seems has been lost somewhere along the way. One of the devs is currently doing a major rework of the bot, so we will add this feature again a bit later on.

Closing as solved

**Closed as completed by NaNraptor** 2018-09-03 13:56 UTC
