### ISSUE TITLE
Cursor stuck on upper left corner of the screen

### ISSUE THREAD

**Issue by RandomFisher** [UltimateFishbot/UltimateFishbot#30] opened 2014-12-11 03:21 UTC
Hi. I've been trying to make Fishbot working with no effect.

Every time I start the Fishbot, it casts fine. However after casting, the mouse cursor goes straight to the upper left corner of the screen and never moves. When I try to move the cursor, it goes back to the corner. As it doesn't try to search the bobber, it appears to do nothing after the splash but release the cursor to be able to move again.

Is there any solution?

**Comment by henrikhermansen** [comment] 2015-01-03 13:09
@RandomFisher are you still having this issue? If so I can try to analyze this a bit more closely, but it does sound like an odd bug. Do you have a multi monitor setup btw?

**Comment by Huddo89** [comment] 2015-01-15 02:33
My issue too. I do have multi monitor, playing vanilla wow. Cursor goes to top left of my right hand (main monitor) I have tried disconnecting my second monitor and restarting with just a single. I have also tried to play wow in my second monitor. Did have a load of mods including xperl, disabled all but to no effect

**Comment by Mograine** [comment] 2015-02-01 14:10
Can you please re-try with the newest version since we re-coded the bobber finder ?

**Comment by henrikhermansen** [comment] 2015-02-01 14:52
@RandomFisher @Huddo89

**Comment by Huddo89** [comment] 2015-02-07 01:22
Still same issue, building new PC within the week with single GPU will test again. *Note playing vanilla wow

**Comment by Muffinek** [comment] 2015-02-15 19:40
i have this problem too, cursor stuck in left top corner, I have only one monitor :/

**Comment by MeiHouwang** [comment] 2015-02-19 18:13
I have the same problem, with cursor going straight to upper left corner. And I have one monitor too. Please fix it.

**Comment by gmillerd** [comment] 2015-04-29 04:53
I am pretty sure you are in windowed mode, but maximized to full screen (no border). Try windowed mode and still be able to see the minimize/maximize/close buttons.

**Comment by vdanielpop** [comment] 2015-05-08 06:19
Has anyone came up with a solution for this? I am running it with WoW 2.4.3, the casting works fine but the mouse goes up in the left corner and just stays there

OS: Windows 8.1
Resolution: 1366x768

EDIT: After a bit of debugging, I got to the GetWowRectangle() method in Win32.cs . For some reason, it doesn't find the window and the pointer that returns is 0, causing the mouse cursor to be stuck in the left corner.

EDIT2: Ok, so the problem was fixed partially, after I replaced
IntPtr Wow = FindWindow("GxWindowClass", "World of Warcraft");
with
IntPtr Wow = FindWindow(null, "World of Warcraft");

The next issue that appeared is that the cursor icon while you hover the bobber is different from the one you use in your app, looks like [this](http://vignette2.wikia.nocookie.net/wowwiki/images/4/46/Pointer_gear_on_32x32.png/revision/latest?cb=20071027070353). I'll try to find a workaround for this issue and will come back with comments later on.

**Comment by gmillerd** [comment] 2015-05-09 16:46
Need to be on the primary display as well, if you have multiple monitors have wow on the primary monitor.

The cursor doesnt matter, its looking for cursor changes so if a monster walks buy during the can it will grab it.

**Comment by vdanielpop** [comment] 2015-05-11 13:07
I am playing on my laptop, so I only have one display.
And I am pretty sure the mouse cursor matters, otherwise, I don't see any way he can establish the initial position of the blobber while surfing the rectangle.

**Comment by gmillerd** [comment] 2015-05-11 16:12
Sorry to hear that, I am sure there are a number of issues with this corner problem. I have a number of monitors and this application only works when the monitor is primary, the cursor always moves over to the primary corner if the window is moved to another monitor.

If you go to display properties and then identify, just make sure the monitor is "1" and not your external monitor if any. To be clear, if you are using another video port it may not be the primary.

On the cursor discussion, the cursor is moved across the window within the x,y x2,y2 area

Ever so often the cursorinfo is checked to see if it has changed, this rate of check is a configuration option.

The detection of the cursor changing is all that is looked for, it doesnt know what changed it, so for example if a enemy walks in the path of the cursor scan, the cursor would change from hand to sword (to attack) and the bobber would be though to have been detected ... and the cursor movement stops.

You can see this easily when you fish in mop areas with monsters on the water surface or when other players walk in front of your bobber.

This is exactly as described in the faq and how the application works in practice.

You can make it detect a bobber pretty easily if you just bring up your bags 'b' key infront of the cursor and it changes when looking at a item to use it.

**Comment by Crystalleaf** [comment] 2015-05-16 12:13
I have solved this problem with 2 changes.
I'm from China so my wow.exe is actually named 魔兽世界 and in this project it is written to be World of Warcraft.
So my solution is:

In the function SendMouseClick() in Classes\helpers\win32.cs 
change the first line from 
IntPtr Wow = FindWindow("GxWindowClass", "World Of Warcraft");
to 
IntPtr Wow = FindWindow(null, "魔兽世界");

Second in the function SendMouseClick() in Classes\helpers\win32.cs 
change the first line from 
IntPtr Wow = FindWindow("GxWindowClass", "World Of Warcraft");
to 
IntPtr Wow = FindWindow(null, "魔兽世界");

After this the program works great on my computer.
Thanks the author~!

**Comment by SoftwareGuyRob** [comment] 2015-05-16 15:16
Thank you @Crystalleaf for your post.

I'm embarrassed to say that I never considered the name of the .exe being different!

**Comment by mullz0r** [comment] 2015-06-30 00:33
Guys.. I have this exact problem. My cursor gets stuck in the top-left part of the screen as the program tries to find the bobber. As I try to move the mouse it keeps moving itself to the top-left corner, so it's definitely doing something. It just doesn't seem to be able to move around inside the WoW window.

I'm a total noob when it comes to code, so I have no idea what Crystalleaf is talking about. Anyone fixed this problem and got a version that works that a noob like me can use?

**Comment by Formeszter** [comment] 2015-08-12 23:26
Hey, Folks. I tried to fish with your bot, but I'm stuck with this problem too!
As far as I can tell I've tried it:
- Fullscreen-Windowed(maxd)-Windowed(usual) none worked! (how to says make it window and shrink it, so regular windowed seems to work, but not for me!)
- Several Cursos Findung settings from both low to both high, high-low and low-high and kinda all possible tries! (none worked)
- Also tried to change code as Crystalleaf did. Re-did all my previous tries! (still not working)

Some other stuff I experienced. As I use latest version with the spiral route alt cursor finding, if that is checked the cursos stays out of game window (but finds it) like its stuck and the border of the window! If not checked it gets inside but stays where wants to stay. 
Somehow I was able to move my mouse from tha starting point, but when casting starts again, it goes back! I tried to take mouse over blobber by hand and waited the bot to 'catch', but nothing happened! Not even heard it. So I started to check about sounding options.
I'm pretty sure others noticed that casting is also with sound (when string touches water it splashes too).
I started to look in the setting, which effect is louder... Well starting splash was usually just 2-3 point less then actual splash!
So I guess putting it the best amount would be hard.
I also tried to put the Delay After Cast timer as high as it cannot hear the start-splash but usually would start before actually catching anything...
After all this noobish tries i looked my Statistics and saw only fish not found numbers...
Can it happen for like it casts and then nothing happened? :S

I also did something that I don't know how, but the bot started to cast fishing so fast like a spammer, like 1cast/sec - If you know why this happened, please tell me!

If anybody wants to know I'm using Win 7 32bit system and playing on 1.12 patch.

So if anybody using the same OS / patch AND can share a working bot with setting via some download I'd appreciate it!

Sorry for the long post, but it is really annoying that I found a quite cool bot and its not working at all!!!

Thanks

**Comment by LaBlazer** [comment] 2015-08-15 22:50
Can you try using the latest version with custom area selection? If that'll work for you, then we can be sure that there is a problem with the bot getting the wow window...

**Comment by Xeiro** [comment] 2015-09-26 15:28
Hello,

I have the same problem. When I download last version, I can not compile it in VS coz of 1 error.

CODE
1>MSBUILD : error : Fody: An unhandled exception occurred:
1>MSBUILD : error : Exception:
1>MSBUILD : error : Unknown custom metadata item kind: 7
1>MSBUILD : error : StackTrace:
1>MSBUILD : error :    at Microsoft.Cci.Pdb.PdbFunction.ReadCustomMetadata(BitAccess bits)
1>MSBUILD : error :    at Microsoft.Cci.Pdb.PdbFunction..ctor(ManProcSym proc, BitAccess bits)
1>MSBUILD : error :    at Microsoft.Cci.Pdb.PdbFunction.LoadManagedFunctions(BitAccess bits, UInt32 limit, Boolean readStrings)
1>MSBUILD : error :    at Microsoft.Cci.Pdb.PdbFile.LoadFuncsFromDbiModule(BitAccess bits, DbiModuleInfo info, IntHashTable names, ArrayList funcList, Boolean readStrings, MsfDirectory dir, Dictionary`2 nameIndex, PdbReader reader)
1>MSBUILD : error :    at Microsoft.Cci.Pdb.PdbFile.LoadFunctions(Stream read, Dictionary`2& tokenToSourceMapping, String& sourceServerData, Int32& age, Guid& guid)
1>MSBUILD : error :    at Mono.Cecil.Pdb.PdbReader.PopulateFunctions()
1>MSBUILD : error :    at Mono.Cecil.Pdb.PdbReader.ProcessDebugHeader(ImageDebugDirectory directory, Byte[] header)
1>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.ProcessDebugHeader()
1>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader)
1>MSBUILD : error :    at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
1>MSBUILD : error :    at Mono.Cecil.ModuleReader.CreateModuleFrom(Image image, ReaderParameters parameters)
1>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.ReadModule(Stream stream, ReaderParameters parameters)
1>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
1>MSBUILD : error :    at InnerWeaver.ReadModule() in c:\TeamCity\buildAgent\work\7495521761d392b9\FodyIsolated\ModuleReader.cs:line 14
1>MSBUILD : error :    at InnerWeaver.Execute() in c:\TeamCity\buildAgent\work\7495521761d392b9\FodyIsolated\InnerWeaver.cs:line 28
1>MSBUILD : error : Source:
1>MSBUILD : error : Mono.Cecil.Pdb
1>MSBUILD : error : TargetSite:
1>MSBUILD : error : Void ReadCustomMetadata(Microsoft.Cci.Pdb.BitAccess)
1>MSBUILD : error : 
1>      Finished Fody 11ms.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
CODE

Can u help me LaBlazer pls?

**Comment by LaBlazer** [comment] 2015-09-27 15:53
Are you compiling it with latest version of VS??

**Comment by Xeiro** [comment] 2015-09-27 17:20
Yes, I am - VS for comunity.

Odesláno z iPhonu
1. 9. 2015 v 17:53, LaBlazer notifications@github.com:

**Comment by LaBlazer** [comment] 2015-09-27 17:26
I just tried to download the code and compiled it from scratch, and it worked without problems... It seems that the fody version is outdated...

**Comment by Xeiro** [comment] 2015-09-27 17:37
I will sound dumb, but what is Fody pls? ;)

Odesláno z iPhonu
1. 9. 2015 v 19:26, LaBlazer notifications@github.com:

**Comment by LaBlazer** [comment] 2015-09-27 17:47
In short Fody is a dependency for Costura and Costura is package that embeds other dependencies as resources into application...

**Comment by LaBlazer** [comment] 2015-09-27 17:54
try to compile it now, ive updated the dependencies...

**Comment by Xeiro** [comment] 2015-09-27 18:59
I just tried to compile lastes version and this is the result:

1>C:\Users\Xeiro\Desktop\UltimateFishbot-CSharp\UltimateFishBot\UltimateFishBot.csproj(212,5): error : This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Fody.1.26.1\build\Fody.targets.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

I do have enabled downloading of the missing packages.

**Comment by LaBlazer** [comment] 2015-09-27 19:18
Yeah, it just happened to me too... i will repair it, but Im unable to run visual studio, because Im updating it from 2013 to 2015

**Comment by Xeiro** [comment] 2015-09-27 19:34
Ok, np. Anyway - i downloaded older version and used fix to recognize wow process (window). I used IntPtr Wow = FindWindow(null, "World of Warcraft");

So now It switch to wow and starts to find bobber. But my problem is, that it is not casting my fishing skill and if I cast it manually, it does not click when it should. So problem is, that it is not sending "key usage" to wow.

Any ideas pls?

**Comment by LaBlazer** [comment] 2015-09-27 19:50
i dont know, try to running it as administrator

**Comment by Xeiro** [comment] 2015-09-27 19:55
Still the same problem.

**Comment by Xeiro** [comment] 2015-09-27 20:16
I got it working - problem was in keyboard layout. I switched it from CZE to ENG and now it cast. I will just need to set sound to actually cast on hearing the fish.

**Comment by LaBlazer** [comment] 2015-09-27 21:16
Thats good to hear. My visual studio will download in a bit, so i will fix the bugs i made :smile: 

(sorry for no english)
P.S.: Ja som zo slovenska, tak som rad, ze sa niekto okrem mna odtialto o tento projekt zaujima :)

**Comment by Xeiro** [comment] 2015-09-28 12:27
Nice, let me know when u fix it :).

(sorry for no english)
Paráda, možná by to chtělo upravit i instrukce k použití programu (třeba to, že musí být ENG kláveska).

**Comment by LaBlazer** [comment] 2015-09-28 16:42
I fixed it now, it is passing appveyor build, so it should now work for you :) just clone clean copy from this repo... And i will update the instructions too when i'll have some time :)

**Comment by DenVredeSnog** [comment] 2015-09-29 10:59
Alright, so it seems like you guys found a solution to the problem with mouse getting stuck in upper left corner when using the fishbot. I'm not that good with coding and i hope you are able to help me out here.

I've downloaded the sourcecode library and found the mentioned file in Classes\helpers\win32.cs. What do i do from here? What exactly do i change and how do i make sure that it effects the .exe file in my library where i keep my fishbot?

I'm sorry if I'm asking for the obvious, but i hope you are able to help me out anyway.

EDIT: I'm using a laptop (1 monitor), Windows 10 and Vanilla Wow

**Comment by LaBlazer** [comment] 2015-09-29 14:13
Have you firstly tried changing the process name from settings?? If it still doesnt work you will need a compiler to compile tgis source code just changing the downloaded file will not do anything. Download Visual Studio 2015 Community from internet (its free) and install it, then open the solution file in the source folder, in IDE navigate to win32 helper class (upper right corner) and then change the code as mentioned in this thread. After you'll change the code you will need to compile it. To do this, press F5 or that little play button in visual studio. If you did everything ok, it should download all dependencies, compile the code and run it. I dont recommend running the bot with debugger attached tgough, because it slows it down... To run it normally you will have to navigate to runnable binary at /bin/Debug/ and run it from there. If you'll get errors try googling them first, there are a lot of answers on the internet already...

**Comment by DenVredeSnog** [comment] 2015-09-29 15:24
Thank you for answering.

First of all; yes, i did try changing the process name in settings - it didn't change anything. (Tried with both 'World of Warcraft' and 'World of Warcraft (32 bit)').

I downloaded VS 2015 and did as you described. I changed 
 public static Rectangle GetWowRectangle()
        {
            IntPtr Wow = FindWindow("GxWindowClass", "World Of Warcraft"); 

to

 public static Rectangle GetWowRectangle()
        {
            IntPtr Wow = FindWindow("null", "World Of Warcraft");

and

public static void SendMouseClick()
        {
            IntPtr Wow = FindWindow("GxWindowClass", "World Of Warcraft");

to

public static void SendMouseClick()
        {
            IntPtr Wow = FindWindow("null", "World Of Warcraft");

I then ran the program using F5 and it started up the fishing bot as intended, the issue is completely the same though. It catches the fishing bobber and the cursor jumps into the upper left corner and stays up there. After a while, VS will maximize and take me to the following code within Classes.BodyParts.Eyes with the option to edit:

throw new Exception("Fish not found"); // Will be catch in Manager:EyeProcess_RunWorkerCompleted

Sorry for being "new", but as people stated earlier - it's such a shame to find this kind of tool and then not being able to use it. 

It's worth mentioning that accessing 'settings' from the botmenu after it's been compiled by VS2015 the process name will be 'Wow'. Vanilla runs with 'World of Warcraft (32 bit)' - could this be a source to the problem?

Thanks a lot in advance

**Comment by LaBlazer** [comment] 2015-09-29 20:33
i dont think this is the fix for you... function FindWindow("GxWindowClass", "World Of Warcraft"); only finds a window with name World of Warcraft. What are you editing in settings is the name of process (executable) that you are running (wow.exe in most cases)... So if you run wow and you have a window named World of Warcraft, this most likely isnt a solution to your problem. You can add me on my skype "wowwac" and i can have a look at it if you want...

**Comment by ExtremeFisherman** [comment] 2015-10-17 17:30
Hi, could this issue have anything to do with tablet drivers ? I see many similar topics mentionning tablets. I tried uninstalling my Wacom drivers but it didn't resolve the problem.

**Comment by LaBlazer** [comment] 2015-10-18 12:38
Sorry, but I dont know about tablets, I dont have any windows tablet to try it on...

**Comment by magnapeccatrix** [comment] 2015-10-19 22:39
Hi all,

I have replaced GxWindowClass with null and compiled codes. Now it casts and scans for bobber all fine but it can not find bobber even if it pass over it. Results in new cast rounds after a while.

Windows 10 Pro, WoW 1.12.1 Client. 
Note: 4.1 Version does not give Fish not found exception but previous versions did.

Could someone please help me out? 

Thanks in advance.

**Comment by LaBlazer** [comment] 2015-10-20 14:26
I dont see any delay in code between detection and looting (hearing fish -> m_manager.HearFish(); -> m_hands.Loot(); -> Win32.SendMouseClick() -> clicks), so im afraid that i wont be able to fix this easily without changing or tweaking the audio library...

**Comment by magnapeccatrix** [comment] 2015-10-20 15:29
Hi Lablazer and thank you for your reply. When I go home I will try on another laptop and report here.

**Comment by magnapeccatrix** [comment] 2015-10-21 07:37
I have tried on another laptop and issue is same. It casts, scans, find bobber, detects splash but loots 3 seconds after splash. So fish escapes.

I have tried with F5 and from /bin exe. All same result.

1.12.1 client. Windows 10.

Could someone help me with this?

Thank you.

**Comment by magnapeccatrix** [comment] 2015-10-21 07:39
I will record a video and post here.

**Comment by LaBlazer** [comment] 2015-10-21 10:11
Did you try to run it as an administrator???

**Comment by magnapeccatrix** [comment] 2015-10-21 14:09
Yes. my friend told me its bcs of audio process delay.  i m on 1.12.1 he said there might be different audio process between latest wow and 1.12 wow.

**Comment by magnapeccatrix** [comment] 2015-10-21 14:12
He told me to replace splash sound in 1.12 with the one in latest wow.

**Comment by magnapeccatrix** [comment] 2015-10-21 19:21
I have uploaded video to below site, I noticed it actually does not hear splash so it does not click to loot.

Now it's more clear what's the problem on 1.12.1 client. 

Please help guys!

http://tinypic.com/r/jzz97q/8

**Comment by magnapeccatrix** [comment] 2015-10-22 07:47
I went to a very silent place and dis fishing on windows 7. caught some fish like 3-5. what is this

**Comment by magnapeccatrix** [comment] 2015-10-22 17:17
Problem solved. Actually answer in my posts.

**Comment by magnapeccatrix** [comment] 2015-10-22 17:18
I have deleted my comments because no one is helping. We have sorted out the problem.

**Comment by LaBlazer** [comment] 2015-10-23 12:53
Sorry, but I was busy with my school... Can you at least tell us how did you fix it??

**Comment by Lenni-s** [comment] 2015-11-13 13:42
Windows 7 uses different then "GxWindowClass" class name. My local fix was to use null instead

**Comment by LaBlazer** [comment] 2015-11-17 12:26
Can you then please download winlister (http://www.nirsoft.net/utils/winlister.html) and tell me what is your class name?

**Comment by Lenni-s** [comment] 2015-11-29 21:38
GxWindowClassD3d

http://imgur.com/hqlaL9Q

**Comment by LaBlazer** [comment] 2015-11-30 08:49
Thank you, i will try to fix it...

**Comment by wowkiller** [comment] 2015-12-06 02:11
I just started playing vanilla wow and tried fishbot but I have the same issue, cursor hits the top left of the desktop and just stays there.  Anyupdate on a fix for that?  I have windows 7 installed and I am using a monitor connected (HDMI) to my Dell laptop.  Thanks!  I look forward to catching some tasty fish!

**Comment by wowkiller** [comment] 2015-12-06 19:39
Is anyone able to use this on Windows 7 with Vanilla Wow and no problems?

**Comment by MonstaKilla** [comment] 2016-02-10 21:12
I tested on WotLK client (probably works with TBC and vanilla too) replacing GxWindowClass with GxWindowClassD3d at SendMouseClick and GetWowRectangle and disabling Check Cursor Icon and works fine. 
According to Winlister, Cata is GxWindowClass so you should have no problem there (probably the same with MoP,WoD). It has probably something to do with the graphical changes during Cata.
Since the icon for bobber mouseover was changed from gear cursor to hook cursor in Cata, having Check Cursor Icon option toggled on while using wotlk or lower will not work.
I tried replacing the .bmp file of the cursor in Resources folder but the mouse didn't stop neither. I tried many gear icons, even screenshotting the one in game (with highest quality) but didn't work. I guess it has something to do with the size of the icon since the method imageCompare checks first if the two images have the same height and width. I noticed that the hook icon has 35x35 but the gear icon i found on WowWiki had 32x32 (screenshotted icon had 28x28 which is a bit odd). It would probably work if someone got the actual image from game data files.

If you have wotlk version or lower just download the newest version of the Fishbot, correct the code lines I mentioned above and toggle off Check Cursor Icon in the settings (don't forget to manually set the scanning area in the settings, the searching is much more efficient if you select the area well). If you have Cata or higher, your problem should be solved by tweaking the Settings.

**Comment by evilpookie** [comment] 2016-02-22 18:50
Thanks for your input MonstaKilla, Downloading VSC now, I'm also having the cursor issue. I'll let you know if i can confirm

Running Vanilla WoW 1.12.1 x32 bit Client
Windows 10

**Comment by evilpookie** [comment] 2016-02-22 21:13
Well, No luck/ I replaced GxWindowClass with GxWindowClassD3d at SendMouseClick
then GetWowRectangle, and disabling Check Cursor Icon.

**Comment by evilpookie** [comment] 2016-02-22 22:30
So, After following the steps provided from everyone, I was able to fix the cursor stuck in the left hand corner issue, however my program doesn't run properly.

Although i did have to make a few changes, Basically i changed "World of Warcraft" to just WoW, only because at first when i renamed everything there was no change. but I noticed when the program is running on my task manager it say's WoW.exe for example;

_

> public static void SendMouseClick()
> {
> IntPtr Wow = FindWindow("null", "World Of Warcraft");

_

Interesting enough Monsta, The bot won't take control of my mouse unless i turn on Check Cursor Icon. So as of now i'm stuck gonna try to toy with it more, I'll keep you updated.

**Comment by evilpookie** [comment] 2016-02-23 17:50
Update*

Following your steps provided Fishbot is working as intended, besides the Anti-AFK function, it crashes the bot every time.

**Comment by Dudein** [comment] 2016-03-22 18:20
Hi guys! :)

I have currently more than lost my mind trying to get this to work...

those thingies you talk about chaning, how and where do i find them to be exact?

If you could specify exactly how, and maybe a path for us (aparently retardos) that would be great!

**Comment by Hexenbane89** [comment] 2016-03-25 22:49
So, anyone solved problem with left corner of the screen ?

**Comment by addis16** [comment] 2016-03-31 18:49
I downloaded the source code, and i made the changes that you guys said to make, but I dont know how to implement the changed code into the ultimatefisher program... can someone please explain to me how to do so?

**Comment by StefanZivanovic** [comment] 2016-04-28 22:18
Hello, i made Github account to ask you. I'm having same problem. I'm don't have skills and i don't know anything about coding. Can someone help me with this by simple download and anything like that? Thanks

**Comment by MetaverseJosh** [comment] 2016-05-31 23:17
Having same issue, has anyone found a fix that doesn't require recompiling stuff?  I don't know jack about code and compiling.  Can someone just upload a fixed version if you have it working?

**Comment by raaloid** [comment] 2016-11-24 16:13
http://www.filedropper.com/fishbot

i compiled it with the necessary changes, re-uploaded...

it's latest version (as of 11/24/2016)

**Comment by Gromgar** [comment] 2016-12-09 14:41
@raaloid 

Unfortunately, your compiled version doesn't work for current Legion patch, cursor is still stuck on top left of screen.

**Comment by dissonanceoflove** [comment] 2017-12-09 13:03
how does this filedropper work? Same problem w10, 1.12.1 client , 1 monitor

**Comment by dissonanceoflove** [comment] 2017-12-22 18:41
MonstaKilla? can you please explain how to edit the prgram in VSC?

**Comment by jesterlol** [comment] 2017-12-31 15:46
can someone compile and upload a version with:
"IntPtr Wow = FindWindow(null, "World Of Warcraft");"

**Comment by hezt** [comment] 2018-01-07 09:59
@Crystalleaf 多谢多谢!

**Comment by ilikefish** [comment] 2018-01-07 17:54
I'm having the exact issue as well. I've tried the latest download, from here: https://github.com/UltimateFishbot/UltimateFishbot/releases/tag/Fishbot-4.0.36

Cursor just sit in the top left hand corner.

I only have the one monitor, I'm on a private server - tbc - 2.4.3. 
If you need any more information, let me know.

**Comment by braczy** [comment] 2018-03-13 01:17
All, I found the issue.  Leaving the code exactly as it is for US/ENGLISH versions, the task manager name of the application for WoW.exe is World of Warcraft.  This also can be seen in the properties of the executable.  The code in the Win32.cs file has two functions:

public static Rectangle GetWowRectangle() 
IntPtr Wow = FindWindow("GxWindowClass", "World Of Warcraft");

This fails because of the capital "O" for Of.  Changing this to lowercase "o" allows the wow window to be found by the fishingbot and the cursor to begin searching within it.

As well as in the function:

public static void SendMouseClick()
IntPtr Wow = FindWindow("GxWindowClass", "World of Warcraft");

Corrected:   IntPtr Wow = FindWindow("GxWindowClass", "World of Warcraft");

After changing these, I rebuilt, published, and executed and works like a charm!

Hope this helps the developer and others!

**Comment by dissonanceoflove** [comment] 2018-03-14 15:11
so braczy could you pls explain me in layperson language how you "changed, rebuilt, published, and executed"? I really want to fish bro pls.
<3

**Comment by pgarrett1121** [comment] 2018-07-26 04:05
Based on @daniel-widrick's work in March / April 2018, it looks like he resolved this issue.  Is this newest version available for download somewhere?

**Comment by daniel-widrick** [comment] 2018-07-31 16:16
I haven't seen any movement from the original dev in awhile:
https://github.com/daniel-widrick/UltimateFishbot/releases

**Comment by pgarrett1121** [comment] 2018-07-31 21:16
Thanks, I'll give it a try tonight

**Comment by NaNraptor** [comment] 2018-08-31 22:00
Fixed

**Closed as completed by NaNraptor** 2018-08-31 22:00 UTC
Labels: bug
