### ISSUE TITLE
AFK mode on dev release

### ISSUE THREAD

**Issue by jensskott** [UltimateFishbot/UltimateFishbot#72] opened 2016-01-19 06:34 UTC
Seems afk mode is crashing the application every times it tries.

**Comment by GrenderG** [comment] 2016-02-12 19:54
Yeah I have noticed it too. 

![captura](https://cloud.githubusercontent.com/assets/8654362/13018607/c29710b2-d1ca-11e5-8d85-75ab4a167d7c.PNG)

**Comment by evilpookie** [comment] 2016-02-23 17:48
Has anyone tried a seperate afk bot to run while fishbot runs?

**Comment by daniel-widrick** [comment] 2018-03-29 17:50
I am unable to reproduce this issue so far.

**Comment by NaNraptor** [comment] 2018-08-31 21:52
me neither... A separate anti-afk bot should work just fine this one

Closing this for now

**Closed as completed by NaNraptor** 2018-08-31 21:52 UTC
