### ISSUE TITLE
Doesn't loot fish

### ISSUE THREAD

**Issue by meking** [UltimateFishbot/UltimateFishbot#24] opened 2014-11-30 20:48 UTC
Everything is working fine but it fails to pick up the fish.
i tried increasing the time "delay after looting" 
none of the settings worked

**Comment by henrikhermansen** [comment] 2014-12-14 02:32
Do you have either the auto looting enabled ingame or the shift-loot setting enabled in the bot? Also make sure you don't have both enabled.
If the above mentioned settings seem correct, could you describe a bit more closely what happens? What does the bot say in its window?

**Comment by henrikhermansen** [comment] 2015-01-03 13:05
@meking  are you still having this issue?

**Comment by Meggity** [comment] 2015-01-07 22:43
Hi there, I am also experiencing this problem. I downloaded the bot yesterday and used ti for 30 mins or so and it appeared to work fine. Today however, it doesn't. The cast is there, the scan appears before the cast, but there is no looting when the fishing sound goes off. Been through the setting numerous times for loot and sound, but still doesn't loot.

**Comment by henrikhermansen** [comment] 2015-01-08 07:09
I see you posted the same in #18 @Meggity. As @meking isn't responding I can't really be certain your two scenarios are exactly the same, but I'll still close this as a duplicate of #18.

**Closed as completed by henrikhermansen** 2015-01-08 07:09 UTC
Labels: bug, duplicate

**Comment by meking** [comment] 2015-01-08 07:21
Hi everyone, sorry for the late response.
the problem is fixed just turn on auto loot.

**Comment by henrikhermansen** [comment] 2015-01-08 07:32
@meking good to hear your issue is resolved!
